name: inventarium
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.7
  collection: ^1.19.1
  data_table_2: ^2.6.0
  equatable: ^2.0.7
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  riverpod_annotation: ^2.6.1
  mobile_scanner: ^3.4.1
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  file_picker: ^10.1.9
  fl_chart: ^0.66.2
  share_plus: ^11.0.0
  http: ^1.4.0
  path_provider: ^2.1.5
  image_picker: ^0.8.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
